services:
  app1:
    build:
      context: ./app1
    ports:
      - "5000:5000"
    container_name: container_app1
    restart: unless-stopped

  app2:
    build:
      context: ./app2
    ports:
      - "5555:5555"
    container_name: container_app2
    restart: unless-stopped